### PANDAS

* pandas is a powerfull python library for manipulation and alanaysis of data

* its a open source library 

* fast(built on top of numpy),flexible(differant resource),productive library

### install

In [82]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [83]:
import pandas as pd

In [84]:
print(pd.__version__)

2.2.3

### Series - one dimensional array (data structure) with label

In [85]:
l1 =[1,2,3,4,5]
type(l1)

list

In [86]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [87]:
s = pd.Series(l1, index = ["apple","banana","a","b","c"], name = "my Series")

In [88]:
s

apple     1
banana    2
a         3
b         4
c         5
Name: my Series, dtype: int64

In [89]:
s['a']

np.int64(3)

In [90]:
type(s)

pandas.core.series.Series

In [91]:
s.index

Index(['apple', 'banana', 'a', 'b', 'c'], dtype='object')

In [92]:
s.values

array([1, 2, 3, 4, 5])

* NOTE :  index in series are imutable (cant change)

In [93]:
s.index[0] = 'z'

TypeError: Index does not support mutable operations

In [ ]:
#  changing the index of series 

s.rename(index={'b':'y'})

apple     1
banana    2
a         3
y         4
c         5
Name: my Series, dtype: int64

In [ ]:
s.rename(index={'b':'y'},inplace=True)

In [ ]:
s

apple     1
banana    2
a         3
y         4
c         5
Name: my Series, dtype: int64

### Dataframe - its a 2d array (just like tables)
rows and cols

In [ ]:
import numpy as np

In [ ]:
dict1 = {'name': ['virat','Rohit','Dhoni','jadeja','Bumrah','Shami'],
        'age':[34,33,40,32,30,28],
        'marks':[85,90,75,80,70,80],
        'Role':['batsman','batsman','wicket keeper','all rounder','bowler','bowler']}

pd.DataFrame(dict1)

     name  age  marks           Role
0   virat   34     85        batsman
1   Rohit   33     90        batsman
2   Dhoni   40     75  wicket keeper
3  jadeja   32     80    all rounder
4  Bumrah   30     70         bowler
5   Shami   28     80         bowler

In [ ]:
df=pd.DataFrame(dict1)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head(2)

    name  age  marks     Role
0  virat   34     85  batsman
1  Rohit   33     90  batsman

In [ ]:
df.tail(2)

     name  age  marks    Role
4  Bumrah   30     70  bowler
5   Shami   28     80  bowler

In [ ]:
len(df)

6

In [ ]:
df.count()

name     6
age      6
marks    6
Role     6
dtype: int64

In [ ]:
df.columns

Index(['name', 'age', 'marks', 'Role'], dtype='object')

In [ ]:
df['name']

0     virat
1     Rohit
2     Dhoni
3    jadeja
4    Bumrah
5     Shami
Name: name, dtype: object

In [ ]:
type(df['name'])

pandas.core.series.Series

In [ ]:
df['name'].value_counts()

name
virat     1
Rohit     1
Dhoni     1
jadeja    1
Bumrah    1
Shami     1
Name: count, dtype: int64

In [ ]:
df['Role'].value_counts()

Role
batsman          2
bowler           2
wicket keeper    1
all rounder      1
Name: count, dtype: int64

### Basic operations

> Importing data set from different files

> Importing tabular dataset

In [ ]:
stock_df = pd.read_csv(r"C:\Users\klemp\Desktop\DataAanalyst (RCB)\dataset\ETH_1h.csv")

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

* Top 5 rows

In [ ]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

* Top 10 rows

In [ ]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

* Bottom 5 rows

In [ ]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

* Number of rows in dataframe

In [ ]:
len(stock_df)

23674

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [ ]:
### accessing a columns in a dataframe
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [ ]:
### accessing multiple columns in a dataframe
stock_df[['Open','Close']]

         Open   Close
0      129.94  128.71
1      119.51  129.94
2      124.47  119.51
3      124.08  124.47
4      124.85  124.08
...       ...     ...
23669  265.74  272.57
23670  268.79  265.74
23671  274.83  268.79
23672  275.01  274.83
23673  279.98  275.01

[23674 rows x 2 columns]

### Accesing rows of dataframe

In [ ]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

## Accessinh rows
* loc-label location

In [ ]:
stock_df.loc[23672]

Date      2017-07-01 12-PM
Symbol              ETHUSD
Open                275.01
High                275.01
Low                  271.0
Close               274.83
Volume           824362.87
Name: 23672, dtype: object

In [ ]:
stock_df.loc[23672,['Date','Open','Close']]

Date     2017-07-01 12-PM
Open               275.01
Close              274.83
Name: 23672, dtype: object

### Slicing in loc (label-location)
* df.loc['row_label_1':'row_label_3','column_label_1':'column_label_2']

In [ ]:
stock_df.loc[23672,'Open':'Close']

Open     275.01
High     275.01
Low       271.0
Close    274.83
Name: 23672, dtype: object

iloc- i index based location,when we dont know labels for rows and columns

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [ ]:
stock_df.loc[1,'Open']

np.float64(119.51)

In [ ]:
stock_df.iloc[2,2]

np.float64(124.47)

In [ ]:
stock_df.iloc[1,2] # row index and volumn index

np.float64(119.51)

In [ ]:
stock_df.iloc[3,[2,4]] # multiple column index

Open    124.08
Low     121.63
Name: 3, dtype: object

In [ ]:
stock_df.iloc[2,2:6] # slicing of columns using iloc

Open     124.47
High     124.85
Low       115.5
Close    119.51
Name: 2, dtype: object

In [ ]:
stock_df.iloc[2:5,2:6]

     Open    High     Low   Close
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08

### filtering

In [ ]:
f1 = stock_df['High'] > 130

In [ ]:
f1

0         True
1         True
2        False
3        False
4        False
         ...
23669     True
23670     True
23671     True
23672     True
23673     True
Name: High, Length: 23674, dtype: bool

In [ ]:
f1 = f1 = stock_df['High'] > 130

stock_gt_130 = stock_df[f1]

In [ ]:
stock_gt_130.reset_index(drop=True,inplace=True)

In [ ]:
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
3      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
4      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
21608  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
21609  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
21610  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
21611  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
21612  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

## Adding new columns

In [ ]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [ ]:
stock_df.iloc[len(stock_df)-1]

Date      2017-07-01 11-AM
Symbol              ETHUSD
Open                279.98
High                279.99
Low                  272.1
Close               275.01
Volume           679358.87
Name: 23673, dtype: object

In [ ]:
len(stock_df)

23674

In [ ]:
range(1,len(stock_df)-1)

range(1, 23673)

In [ ]:
stock_df['Random_col'] = list(range(1,len(stock_df)+1))

In [ ]:
stock_df

,Date,Symbol,Open,High,Low,Close,Volume,Random_col
0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,1
1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,2
2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,3
3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,4
4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,5
...,...,...,...,...,...,...,...,...
23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,23670
23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,23671
23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,23672
23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87,23673
23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87,23674

### Dropping column

In [101]:
stock_df.drop(Columns=['Random_col'],inplace=True)

TypeError: DataFrame.drop() got an unexpected keyword argument 'Columns'. Did you mean 'columns'?

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [ ]:
stock_df.drop(columns=['Open','High'],inplace=True)

In [ ]:
stock_df

                   Date  Symbol     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
...                 ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87

[23674 rows x 5 columns]

In [ ]:
stock_df.drop(Columns=['Open','High'],axis=1,inplace=True) # 1 - columns

TypeError: DataFrame.drop() got an unexpected keyword argument 'Columns'. Did you mean 'columns'?